In [3]:
import pandas as pd
import matplotlib.pylab as plt
import numpy as np
import scipy.optimize as ops
from sklearn import preprocessing
%matplotlib inline
 


In [4]:
df=pd.read_csv("ChurnData.csv")
df.head()


tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   

   longmon  ...  pager  internet  callwait  confer  ebill  loglong  logtoll  \
0     4.40  ...    1.0       0.0       1.0     1.0    0.0    1.482    3.033   
1     9.45  ...    0.0       0.0       0.0     0.0    0.0    2.246    3.240   
2     6.30  ...    0.0       0.0       0.0     1.0    0.0    1.841    3.240   
3     6.05  ...    1.0       1.0       1.0     1.0    1.0    1.800    3.807   
4     7.10  ...    0.0       0.0       1.0     1.0    0.0    1.960    3.091   

   lninc  custcat  churn  
0  4.913      4.0    1.0  
1  3.497      1.0    1.0  
2  3.401      3.0    0.0  
3  4.331      4.0    0.0  
4  4.382      3.0    0.0  

[5 rows x 28 columns]

In [5]:
df =df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip',   'callcard', 'wireless','churn']]
df['churn'] =df['churn'].astype('int')


In [6]:
X = np.asarray(df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip']])
X[0:10]

array([[ 11.,  33.,   7., 136.,   5.,   5.,   0.],
       [ 33.,  33.,  12.,  33.,   2.,   0.,   0.],
       [ 23.,  30.,   9.,  30.,   1.,   2.,   0.],
       [ 38.,  35.,   5.,  76.,   2.,  10.,   1.],
       [  7.,  35.,  14.,  80.,   2.,  15.,   0.],
       [ 68.,  52.,  17., 120.,   1.,  24.,   0.],
       [ 42.,  40.,   7.,  37.,   2.,   8.,   1.],
       [  9.,  21.,   1.,  17.,   2.,   2.,   0.],
       [ 35.,  50.,  26., 140.,   2.,  21.,   0.],
       [ 49.,  51.,  27.,  63.,   4.,  19.,   0.]])

In [7]:
y=np.asarray(df[["churn"]])
y[0:5]

array([[1],
       [1],
       [0],
       [0],
       [0]])

In [8]:
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

array([[-1.13518441, -0.62595491, -0.4588971 ,  0.4751423 ,  1.6961288 ,
        -0.58477841, -0.85972695],
       [-0.11604313, -0.62595491,  0.03454064, -0.32886061, -0.6433592 ,
        -1.14437497, -0.85972695],
       [-0.57928917, -0.85594447, -0.261522  , -0.35227817, -1.42318853,
        -0.92053635, -0.85972695],
       [ 0.11557989, -0.47262854, -0.65627219,  0.00679109, -0.6433592 ,
        -0.02518185,  1.16316   ],
       [-1.32048283, -0.47262854,  0.23191574,  0.03801451, -0.6433592 ,
         0.53441472, -0.85972695]])

In [9]:
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y=train_test_split(X,y,test_size=0.2,random_state=1)
print(train_x.shape,train_y.shape)
print(test_x.shape,test_y.shape)

(160, 7) (160, 1)
(40, 7) (40, 1)


In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR=LogisticRegression(C=0.01, solver='liblinear').fit(train_x,train_y)
LR


D:\python-env\lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=0.01, solver='liblinear')

In [11]:
y_hat=LR.predict(test_x)
y_hat

array([1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1])

In [12]:
yhat_proba=LR.predict_proba(test_x)
yhat_proba

array([[0.42147528, 0.57852472],
       [0.41177723, 0.58822277],
       [0.51662441, 0.48337559],
       [0.52144603, 0.47855397],
       [0.67237214, 0.32762786],
       [0.47706213, 0.52293787],
       [0.46991268, 0.53008732],
       [0.55488061, 0.44511939],
       [0.44191987, 0.55808013],
       [0.63689587, 0.36310413],
       [0.46851288, 0.53148712],
       [0.50214076, 0.49785924],
       [0.53852403, 0.46147597],
       [0.45926809, 0.54073191],
       [0.60999156, 0.39000844],
       [0.52726409, 0.47273591],
       [0.45246568, 0.54753432],
       [0.73729328, 0.26270672],
       [0.43471348, 0.56528652],
       [0.41190709, 0.58809291],
       [0.54020177, 0.45979823],
       [0.46835496, 0.53164504],
       [0.46889641, 0.53110359],
       [0.73859349, 0.26140651],
       [0.7569182 , 0.2430818 ],
       [0.58505419, 0.41494581],
       [0.5641001 , 0.4358999 ],
       [0.45842287, 0.54157713],
       [0.71384089, 0.28615911],
       [0.53127887, 0.46872113],
       [0.

In [18]:
from sklearn.metrics import jaccard_score
jaccard_score(test_y,y_hat,pos_label=0)

0.75

In [13]:
from sklearn.metrics import classification_report, confusion_matrix
confusion_matrix(test_y,y_hat)

array([[24,  7],
       [ 1,  8]], dtype=int64)

In [14]:
print (classification_report(test_y,y_hat))

              precision    recall  f1-score   support

           0       0.96      0.77      0.86        31
           1       0.53      0.89      0.67         9

    accuracy                           0.80        40
   macro avg       0.75      0.83      0.76        40
weighted avg       0.86      0.80      0.81        40



In [15]:
from sklearn.metrics import log_loss
log_loss(test_y,yhat_proba)

0.5867051755252554

In [16]:
LR2 = LogisticRegression(C=0.01, solver='sag').fit(train_x,train_y)
yhat_prob2 = LR2.predict_proba(test_x)
print ("LogLoss: : %.2f" % log_loss(test_y, yhat_prob2))

LogLoss: : 0.49


D:\python-env\lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
